"use client";
import { useActionState } from "react";
import { addPaymentAction, createDebtAction, type FormState } from "@/lib/actions/ledger";
import { Button } from "@/components/ui/Button";
import { Input, Label, Select, Textarea } from "@/components/ui/Input";
import { InlineFormMessage } from "@/components/ui/InlineFormMessage";
import type { Client, LedgerProduct } from "@/lib/types";
const state: FormState = {};
export function NewDebtForm({ clients, products }: { clients: Client[]; products: LedgerProduct[] }) { const [result, action, pending] = useActionState(createDebtAction, state); if (!clients.length || !products.length) return <p className="rounded-xl bg-primary-tint p-3 text-sm text-primary">Avval kamida bitta mijoz va zaxirada mahsulot qo‘shing.</p>; return <form action={action} className="space-y-3"><div><Label htmlFor="clientId">Mijoz</Label><Select id="clientId" name="clientId" required defaultValue=""><option value="" disabled>Mijozni tanlang</option>{clients.map((c) => <option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</Select></div><div><Label htmlFor="productId">Mahsulot</Label><Select id="productId" name="productId" required defaultValue=""><option value="" disabled>Mahsulotni tanlang</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.price} so‘m ({p.stock} dona)</option>)}</Select></div><div><Label htmlFor="quantity">Miqdor</Label><Input id="quantity" name="quantity" type="number" min="1" defaultValue="1" required /></div><div><Label htmlFor="notes">Izoh (ixtiyoriy)</Label><Textarea id="notes" name="notes" rows={2} placeholder="Masalan, oy oxirida beradi" /></div><InlineFormMessage {...result} /><Button className="w-full" disabled={pending}>{pending ? "Yozilmoqda…" : "Qarzga yozish"}</Button></form>; }
export function PaymentForm({ debtId, max }: { debtId: string; max: number }) { const [result, action, pending] = useActionState(addPaymentAction, state); return <form action={action} className="min-w-36"><input type="hidden" name="debtId" value={debtId} /><Input name="amount" type="number" min="1" max={max} placeholder="To‘lov" required /><InlineFormMessage {...result} /><Button size="sm" className="mt-2 w-full" disabled={pending}>{pending ? "…" : "To‘lov"}</Button></form>; }
